// Auto-generated by extract-methods.mjs — do not edit manually
export const BPM_METHODS = {
  HOME_LIST: "BpmApiExpenseUrl-Home-List",
  RECEIPT_ADD: "BpmApiExpenseUrl-Receipt-Add",
  RECEIPT_DETAIL: "BpmApiExpenseUrl-Receipt-Detail",
  RECEIPT_GETRECEIPTTYPE: "BpmApiExpenseUrl-Receipt-GetReceiptType",
  RECEIPT_LIST: "BpmApiExpenseUrl-Receipt-List",
  RECEIPT_RECOGNIZE: "BpmApiExpenseUrl-Receipt-Recognize",
  RECEIPT_REMOVE: "BpmApiExpenseUrl-Receipt-Remove",
  CATEGORY_LIST: "BpmApiHomeUrl-Category-List",
  DIARY_ADD: "BpmApiHomeUrl-Diary-Add",
  DIARY_LIST: "BpmApiHomeUrl-Diary-List",
  DIARY_REMOVE: "BpmApiHomeUrl-Diary-Remove",
  DIARYSUPERVISOR_LIST: "BpmApiHomeUrl-DiarySupervisor-List",
  DIARYSUPERVISOR_MODIFY: "BpmApiHomeUrl-DiarySupervisor-Modify",
  HOME_CURRENCY: "BpmApiHomeUrl-Home-Currency",
  HOME_CUSTOMER: "BpmApiHomeUrl-Home-Customer",
  HOME_EXTENSION: "BpmApiHomeUrl-Home-Extension",
  HOME_GETBPM: "BpmApiHomeUrl-Home-GetBpm",
  HOME_STAFF: "BpmApiHomeUrl-Home-Staff",
  HOME_TAG: "BpmApiHomeUrl-Home-Tag",
  PRODUCT_ADD: "BpmApiHomeUrl-Product-Add",
  PRODUCT_DETAIL: "BpmApiHomeUrl-Product-Detail",
  PRODUCT_LIST: "BpmApiHomeUrl-Product-List",
  PRODUCT_MODIFY: "BpmApiHomeUrl-Product-Modify",
  QUOTATION_DETAIL: "BpmApiHomeUrl-Quotation-Detail",
  QUOTATION_LIST: "BpmApiHomeUrl-Quotation-List",
  HISTORY_LIST: "WorkflowApiUrl-History-List",
  NOTIFY_LIST: "WorkflowApiUrl-Notify-List",
  TASK_LIST: "WorkflowApiUrl-Task-List",
} as const

export type BpmMethod =
  (typeof BPM_METHODS)[keyof typeof BPM_METHODS];
