// Auto-generated by extract-methods.mjs — do not edit manually
export const CAR_METHODS = {
  CAR_VERIFYSTAFF: "TmcApiCarUrl-Car-VerifyStaff",
  HOME_PICKUPSTORE: "TmcApiRentalCarUrl-Home-PickupStore",
  HOME_RETURNSTORE: "TmcApiRentalCarUrl-Home-ReturnStore",
  HOME_SEARCH: "TmcApiRentalCarUrl-Home-Search",
  CAR_VERIFYSTAFF_4: "TmcTouristCarUrl-Car-VerifyStaff",
} as const

export type CarMethod =
  (typeof CAR_METHODS)[keyof typeof CAR_METHODS];
