// Auto-generated by extract-methods.mjs — do not edit manually
export const FLIGHT_METHODS = {
  HOME_DETAIL: "TmcApiFlightDynamicUrl-Home-Detail",
  HOME_SEARCH: "TmcApiFlightDynamicUrl-Home-Search",
  HOME_DETAIL_2: "TmcApiFlightUrl-Home-Detail",
  HOME_EXCHANGE: "TmcApiFlightUrl-Home-Exchange",
  HOME_EXCHANGEDETAIL: "TmcApiFlightUrl-Home-ExchangeDetail",
  HOME_INDEX: "TmcApiFlightUrl-Home-Index",
  HOME_POLICY: "TmcApiFlightUrl-Home-Policy",
  HOME_CHECK: "TmcApiInternationalFlightUrl-Home-Check",
  HOME_CHECKROUTEPOLICY: "TmcApiInternationalFlightUrl-Home-CheckRoutePolicy",
  HOME_DETAIL_9: "TmcApiInternationalFlightUrl-Home-Detail",
  HOME_FLIGHTCABINLEVELPOLICY: "TmcApiInternationalFlightUrl-Home-FlightCabinLevelPolicy",
  HOME_GETRULEINFO: "TmcApiInternationalFlightUrl-Home-GetRuleInfo",
  HOME_GETSTOPCITIES: "TmcApiInternationalFlightUrl-Home-GetStopCities",
  HOME_INDEX_13: "TmcApiInternationalFlightUrl-Home-Index",
  HOME_DETAIL_14: "TmcTouristFlightUrl-Home-Detail",
  HOME_EXCHANGE_15: "TmcTouristFlightUrl-Home-Exchange",
  HOME_EXCHANGEDETAIL_16: "TmcTouristFlightUrl-Home-ExchangeDetail",
  HOME_INDEX_17: "TmcTouristFlightUrl-Home-Index",
} as const

export type FlightMethod =
  (typeof FLIGHT_METHODS)[keyof typeof FLIGHT_METHODS];
