import { BOOK_METHODS } from "./book.js";
import { FLIGHT_METHODS } from "./flight.js";
import { TMC_METHODS } from "./tmc.js";

/** Curated S5 flight flow Methods (search + list + detail). */
export const FLIGHT_FLOW_METHODS = {
  RESOURCE_AIRPORT: TMC_METHODS.RESOURCE_AIRPORT,
  HOME_INDEX: FLIGHT_METHODS.HOME_INDEX,
  HOME_DETAIL: FLIGHT_METHODS.HOME_DETAIL_2,
  HOME_POLICY: FLIGHT_METHODS.HOME_POLICY,
} as const;

export const TOURIST_FLIGHT_FLOW_METHODS = {
  RESOURCE_AIRPORT: TMC_METHODS.RESOURCE_AIRPORT,
  HOME_INDEX: FLIGHT_METHODS.HOME_INDEX_17,
  HOME_DETAIL: FLIGHT_METHODS.HOME_DETAIL_14,
  HOME_EXCHANGE: FLIGHT_METHODS.HOME_EXCHANGE_15,
  HOME_EXCHANGE_DETAIL: FLIGHT_METHODS.HOME_EXCHANGEDETAIL_16,
} as const;

export const TOURIST_FLIGHT_BOOK_METHODS = {
  INIT: BOOK_METHODS.FLIGHT_INITIALIZE_33,
  VALIDATE: BOOK_METHODS.FLIGHT_VALIDATE,
  BOOK: BOOK_METHODS.FLIGHT_BOOK_30,
  EXCHANGE_INIT: BOOK_METHODS.FLIGHT_EXCHANGEINITIALIZE,
  EXCHANGE_BOOK: BOOK_METHODS.FLIGHT_EXCHANGEBOOK_31,
} as const;

export type FlightFlowMethod =
  (typeof FLIGHT_FLOW_METHODS)[keyof typeof FLIGHT_FLOW_METHODS];

export type TouristFlightFlowMethod =
  (typeof TOURIST_FLIGHT_FLOW_METHODS)[keyof typeof TOURIST_FLIGHT_FLOW_METHODS];

export type TouristFlightBookMethod =
  (typeof TOURIST_FLIGHT_BOOK_METHODS)[keyof typeof TOURIST_FLIGHT_BOOK_METHODS];
