// Auto-generated by extract-methods.mjs — do not edit manually
export const HOTEL_METHODS = {
  CITY_GETCITYBYMAP: "TmcApiHotelUrl-City-GetCityByMap",
  CONDITION_GETS: "TmcApiHotelUrl-Condition-Gets",
  _: "TmcApiHotelUrl-Home",
  HOME_DETAIL: "TmcApiHotelUrl-Home-Detail",
  HOME_LIST: "TmcApiHotelUrl-Home-List",
  HOME_POLICY: "TmcApiHotelUrl-Home-Policy",
  HOME_RECOMMENDHOTEL: "TmcApiHotelUrl-Home-RecommendHotel",
  HOME_SEARCHHOTEL: "TmcApiHotelUrl-Home-SearchHotel",
  CONDITION_GETS_8: "TmcApiInternationalHotelUrl-Condition-Gets",
  COUNTRY_GETCOUTRIES: "TmcApiInternationalHotelUrl-Country-GetCoutries",
  HOME_DETAIL_10: "TmcApiInternationalHotelUrl-Home-Detail",
  HOME_LIST_11: "TmcApiInternationalHotelUrl-Home-List",
  HOME_POLICY_12: "TmcApiInternationalHotelUrl-Home-Policy",
  HOME_SEARCHHOTEL_13: "TmcApiInternationalHotelUrl-Home-SearchHotel",
  TRAFFICLINE_SEARCH: "TmcApiInternationalHotelUrl-Trafficline-Search",
  BOOK_BOOK: "TmcTouristHotelUrl-Book-Book",
  CITY_GETCITYBYMAP_16: "TmcTouristHotelUrl-City-GetCityByMap",
  CITY_GETS: "TmcTouristHotelUrl-City-Gets",
  CONDITION_GETS_18: "TmcTouristHotelUrl-Condition-Gets",
  HOME_DETAIL_19: "TmcTouristHotelUrl-Home-Detail",
  HOME_LIST_20: "TmcTouristHotelUrl-Home-List",
  HOME_SEARCHHOTEL_21: "TmcTouristHotelUrl-Home-SearchHotel",
} as const

export type HotelMethod =
  (typeof HOTEL_METHODS)[keyof typeof HOTEL_METHODS];
