// Auto-generated by extract-methods.mjs — do not edit manually
export const MEMBER_METHODS = {
  ACCOUNTCARD_LIST: "ApiAccountUrl-AccountCard-List",
  ACCOUNTCARD_REMOVE: "ApiAccountUrl-AccountCard-Remove",
  HOME_GET: "ApiAccountUrl-Home-Get",
  HOME_GETBALANCE: "ApiAccountUrl-Home-GetBalance",
  HOME_GETITEMS: "ApiAccountUrl-Home-GetItems",
  HOME_LOGOUT: "ApiAccountUrl-Home-Logout",
  MESSAGE_GETCOUNT: "ApiAccountUrl-Message-GetCount",
  MESSAGE_POP: "ApiAccountUrl-Message-Pop",
  MESSAGE_READ: "ApiAccountUrl-Message-Read",
  MESSAGE_REMOVE: "ApiAccountUrl-Message-Remove",
  MESSAGE_SHOW: "ApiAccountUrl-Message-Show",
  ADDRESS_ADD: "ApiMemberUrl-Address-Add",
  ADDRESS_LIST: "ApiMemberUrl-Address-List",
  ADDRESS_MODIFY: "ApiMemberUrl-Address-Modify",
  ADDRESS_REMOVE: "ApiMemberUrl-Address-Remove",
  COUPON_LIST: "ApiMemberUrl-Coupon-List",
  COUPON_REMOVE: "ApiMemberUrl-Coupon-Remove",
  MEMBER_GET: "ApiMemberUrl-Member-Get",
  MEMBER_GETACCOUNT: "ApiMemberUrl-Member-GetAccount",
  MEMBER_SAVE: "ApiMemberUrl-Member-Save",
  PASSENGER_ADD: "ApiMemberUrl-Passenger-Add",
  PASSENGER_LIST: "ApiMemberUrl-Passenger-List",
  PASSENGER_MODIFY: "ApiMemberUrl-Passenger-Modify",
  PASSENGER_REMOVE: "ApiMemberUrl-Passenger-Remove",
  COUPON_COLLECT: "MmsApiMemberUrl-Coupon-Collect",
} as const

export type MemberMethod =
  (typeof MEMBER_METHODS)[keyof typeof MEMBER_METHODS];
