import { MEMBER_METHODS } from "./member.js";

/** Curated S4 member / passenger Methods. */
export const MEMBER_FLOW_METHODS = {
  PASSENGER_LIST: MEMBER_METHODS.PASSENGER_LIST,
  PASSENGER_ADD: MEMBER_METHODS.PASSENGER_ADD,
  PASSENGER_MODIFY: MEMBER_METHODS.PASSENGER_MODIFY,
  PASSENGER_REMOVE: MEMBER_METHODS.PASSENGER_REMOVE,
  MEMBER_GET: MEMBER_METHODS.MEMBER_GET,
} as const;

export type MemberFlowMethod =
  (typeof MEMBER_FLOW_METHODS)[keyof typeof MEMBER_FLOW_METHODS];
