// Auto-generated by extract-methods.mjs — do not edit manually
export const MMS_METHODS = {
  SETTLEMENT_BUY: "MmsApiBuyUrl-Settlement-Buy",
  SETTLEMENT_INDEX: "MmsApiBuyUrl-Settlement-Index",
  BANNER_LIST: "MmsApiHomeUrl-Banner-List",
  COMPANY_DETAIL: "MmsApiHomeUrl-Company-Detail",
  COUPON_LIST: "MmsApiHomeUrl-Coupon-List",
  HOME_GETMMS: "MmsApiHomeUrl-Home-GetMms",
  SITEMAP_LIST: "MmsApiHomeUrl-Sitemap-List",
  TAG_LIST: "MmsApiHomeUrl-Tag-List",
  CATEGORY_LIST: "MmsApiProductUrl-Category-List",
  GOODS_DETAIL: "MmsApiProductUrl-Goods-Detail",
  GOODS_LIST: "MmsApiProductUrl-Goods-List",
  GOODS_SEARCH: "MmsApiProductUrl-Goods-Search",
  SHOPCART_ADD: "MmsApiShopcartUrl-Shopcart-Add",
  SHOPCART_CLEAR: "MmsApiShopcartUrl-Shopcart-Clear",
  SHOPCART_GETCOUNT: "MmsApiShopcartUrl-Shopcart-GetCount",
  SHOPCART_LIST: "MmsApiShopcartUrl-Shopcart-List",
  SHOPCART_MODIFY: "MmsApiShopcartUrl-Shopcart-Modify",
  SHOPCART_REMOVE: "MmsApiShopcartUrl-Shopcart-Remove",
  LOTTERY_BUY: "MmsApiStoreUrl-Lottery-Buy",
  LOTTERY_CREATE: "MmsApiStoreUrl-Lottery-Create",
  LOTTERY_USE: "MmsApiStoreUrl-Lottery-Use",
  WECHATCARD_BUY: "MmsApiStoreUrl-WechatCard-Buy",
  WECHATCARD_CREATE: "MmsApiStoreUrl-WechatCard-Create",
  WECHATCARD_USE: "MmsApiStoreUrl-WechatCard-Use",
} as const

export type MmsMethod =
  (typeof MMS_METHODS)[keyof typeof MMS_METHODS];
