import { ORDER_METHODS } from "./order.js";

/** Curated S3 order / pay flow Methods. */
export const ORDER_FLOW_METHODS = {
  LIST: ORDER_METHODS.ORDER_LIST_36,
  DETAIL: ORDER_METHODS.ORDER_DETAIL_27,
  CANCEL_HOTEL: ORDER_METHODS.ORDER_CANCELORDERHOTEL,
  CANCEL_TRAIN: ORDER_METHODS.ORDER_CANCELTRAIN,
  ISSUE_TRAIN: ORDER_METHODS.ORDER_ISSUETRAIN,
  TRAIN_REFUND: ORDER_METHODS.TRAIN_REFUND,
  SEND_HOTEL_SMS: ORDER_METHODS.ORDER_SENDVERIFYORDERHOTELSMSCODE,
  CONFIRM_HOTEL_SMS: ORDER_METHODS.ORDER_CONFIRMVERIFYORDERHOTELSMSCODE,
  CHECK_INSPUR_REPUSH: ORDER_METHODS.ORDER_CHECKINSPURREPUSH,
  ABOLISH_ORDER: ORDER_METHODS.ORDER_ABOLISHORDER,
  ABOLISH_TICKET: ORDER_METHODS.ORDER_ABOLISHTICKET,
  GET_FLIGHT_TICKET_REFUND_INFO: ORDER_METHODS.ORDER_GETFLIGHTTICKETREFUNDINFO,
  REFUND_FLIGHT: ORDER_METHODS.ORDER_REFUNDFLIGHT,
  NON_VOLUNTARY_REFUND_FLIGHT: ORDER_METHODS.ORDER_NONVOLUNTARYREFUNDFLIGHT,
  GET_ORDER_PAYS: ORDER_METHODS.ORDER_GETORDERPAYS,
  GET_TOTAL_PAY_AMOUNT: ORDER_METHODS.PAY_GETTOTALPAYAMOUNT,
  PAY_CREATE: "TmcApiOrderUrl-Pay-Create",
  PAY_PROCESS: "TmcApiOrderUrl-Pay-Process",
  TRAVEL_LIST: ORDER_METHODS.TRAVEL_LIST,
} as const;

export const TOURIST_ORDER_FLOW_METHODS = {
  LIST: ORDER_METHODS.ORDER_LIST_57,
  DETAIL: ORDER_METHODS.ORDER_DETAIL_53,
  CANCEL_HOTEL: ORDER_METHODS.ORDER_CANCELORDERHOTEL_50,
  CANCEL_TRAIN: ORDER_METHODS.ORDER_CANCELTRAIN_51,
  ISSUE_TRAIN: ORDER_METHODS.ORDER_ISSUETRAIN_56,
  SEND_HOTEL_SMS: ORDER_METHODS.ORDER_SENDVERIFYORDERHOTELSMSCODE_59,
  CONFIRM_HOTEL_SMS: ORDER_METHODS.ORDER_CONFIRMVERIFYORDERHOTELSMSCODE_52,
  ABOLISH_ORDER: ORDER_METHODS.ORDER_ABOLISHORDER_48,
  ABOLISH_TICKET: ORDER_METHODS.ORDER_ABOLISHTICKET_49,
  REFUND_FLIGHT: ORDER_METHODS.ORDER_REFUNDFLIGHT_58,
  GET_ORDER_PAYS: ORDER_METHODS.ORDER_GETORDERPAYS_55,
  GET_TOTAL_PAY_AMOUNT: ORDER_METHODS.PAY_GETTOTALPAYAMOUNT_62,
  PAY_CREATE: ORDER_METHODS.PAY_CREATE,
  PAY_PROCESS: ORDER_METHODS.PAY_PROCESS,
  PAY_GET_ORDER_PAYS: ORDER_METHODS.PAY_GETORDERPAYS,
  TASK_LIST: ORDER_METHODS.TASK_LIST_64,
  TRAVEL_LIST: ORDER_METHODS.TRAVEL_LIST_65,
  INSURANCE_BOOK: ORDER_METHODS.INSURANCE_BOOK_47,
} as const;

export type OrderFlowMethod = (typeof ORDER_FLOW_METHODS)[keyof typeof ORDER_FLOW_METHODS];

export type TouristOrderFlowMethod =
  (typeof TOURIST_ORDER_FLOW_METHODS)[keyof typeof TOURIST_ORDER_FLOW_METHODS];
