import { ORDER_METHODS } from "./order.js";

/** Curated S3 order / pay flow Methods. */
export const ORDER_FLOW_METHODS = {
  LIST: ORDER_METHODS.ORDER_LIST_36,
  DETAIL: ORDER_METHODS.ORDER_DETAIL_27,
  CANCEL_HOTEL: ORDER_METHODS.ORDER_CANCELORDERHOTEL,
  CANCEL_TRAIN: ORDER_METHODS.ORDER_CANCELTRAIN,
  ISSUE_TRAIN: ORDER_METHODS.ORDER_ISSUETRAIN,
  TRAIN_REFUND: ORDER_METHODS.TRAIN_REFUND,
  SEND_HOTEL_SMS: ORDER_METHODS.ORDER_SENDVERIFYORDERHOTELSMSCODE,
  CONFIRM_HOTEL_SMS: ORDER_METHODS.ORDER_CONFIRMVERIFYORDERHOTELSMSCODE,
  CHECK_INSPUR_REPUSH: ORDER_METHODS.ORDER_CHECKINSPURREPUSH,
  ABOLISH_ORDER: ORDER_METHODS.ORDER_ABOLISHORDER,
  ABOLISH_TICKET: ORDER_METHODS.ORDER_ABOLISHTICKET,
  GET_ORDER_PAYS: ORDER_METHODS.ORDER_GETORDERPAYS,
  GET_TOTAL_PAY_AMOUNT: ORDER_METHODS.PAY_GETTOTALPAYAMOUNT,
  PAY_CREATE: "TmcApiOrderUrl-Pay-Create",
  PAY_PROCESS: "TmcApiOrderUrl-Pay-Process",
  TRAVEL_LIST: ORDER_METHODS.TRAVEL_LIST,
} as const;

export type OrderFlowMethod = (typeof ORDER_FLOW_METHODS)[keyof typeof ORDER_FLOW_METHODS];
