import { AUTH_METHODS } from "./auth.js";

/** Curated account security / password Methods. */
export const PASSWORD_FLOW_METHODS = {
  PASSWORD_MODIFY: AUTH_METHODS.PASSWORD_MODIFY,
  MOBILE_LOAD: AUTH_METHODS.MOBILE_LOAD,
  MOBILE_SENDCODE: AUTH_METHODS.MOBILE_SENDCODE,
  MOBILE_ACTION: AUTH_METHODS.MOBILE_ACTION,
  EMAIL_LOAD: AUTH_METHODS.EMAIL_LOAD,
  EMAIL_SENDCODE: AUTH_METHODS.EMAIL_SENDCODE,
  EMAIL_ACTION: AUTH_METHODS.EMAIL_ACTION,
  DEVICE_LIST: AUTH_METHODS.DEVICE_LIST,
  DEVICE_REMOVE: AUTH_METHODS.DEVICE_REMOVE,
} as const;

export type PasswordFlowMethod = (typeof PASSWORD_FLOW_METHODS)[keyof typeof PASSWORD_FLOW_METHODS];
