import { BOOK_METHODS } from "./book.js";
import { TRAIN_METHODS } from "./train.js";
import { TMC_METHODS } from "./tmc.js";

export const TRAIN_FLOW_METHODS = {
  RESOURCE_STATION: TMC_METHODS.RESOURCE_TRAINSTATION,
  HOME_SEARCH: TRAIN_METHODS.HOME_SEARCH,
  POLICY: TRAIN_METHODS.HOME_POLICY,
  GET_EXCHANGE_INFO: TRAIN_METHODS.HOME_GETEXCHANGEINFO,
  GET_TRAIN_PASSENGER: TRAIN_METHODS.HOME_GETTRAINPASSENGER,
  SCHEDULE: TRAIN_METHODS.HOME_SCHEDULE,
  INIT: BOOK_METHODS.TRAIN_INITIALIZE,
  BOOK: BOOK_METHODS.TRAIN_BOOK,
  EXCHANGE_BOOK: BOOK_METHODS.TRAIN_EXCHANGEBOOK,
} as const;

export type TrainFlowMethod =
  (typeof TRAIN_FLOW_METHODS)[keyof typeof TRAIN_FLOW_METHODS];
