// Auto-generated by extract-methods.mjs — do not edit manually
export const TRAIN_METHODS = {
  HOME_GETEXCHANGEINFO: "TmcApiTrainUrl-Home-GetExchangeInfo",
  HOME_GETTRAINPASSENGER: "TmcApiTrainUrl-Home-GetTrainPassenger",
  HOME_POLICY: "TmcApiTrainUrl-Home-Policy",
  HOME_SCHEDULE: "TmcApiTrainUrl-Home-Schedule",
  HOME_SEARCH: "TmcApiTrainUrl-Home-Search",
  HOME_GETEXCHANGEINFO_5: "TmcTouristTrainUrl-Home-GetExchangeInfo",
  HOME_GETTRAINPASSENGER_6: "TmcTouristTrainUrl-Home-GetTrainPassenger",
  HOME_POLICY_7: "TmcTouristTrainUrl-Home-Policy",
  HOME_REFUND: "TmcTouristTrainUrl-Home-Refund",
  HOME_SCHEDULE_9: "TmcTouristTrainUrl-Home-Schedule",
  HOME_SEARCH_10: "TmcTouristTrainUrl-Home-Search",
} as const

export type TrainMethod =
  (typeof TRAIN_METHODS)[keyof typeof TRAIN_METHODS];
