import { BOOK_METHODS } from "./book.js";
import { TRAIN_METHODS } from "./train.js";
import { TMC_METHODS } from "./tmc.js";

export const TRAIN_FLOW_METHODS = {
  RESOURCE_STATION: TMC_METHODS.RESOURCE_TRAINSTATION,
  HOME_SEARCH: TRAIN_METHODS.HOME_SEARCH,
  POLICY: TRAIN_METHODS.HOME_POLICY,
  GET_EXCHANGE_INFO: TRAIN_METHODS.HOME_GETEXCHANGEINFO,
  GET_TRAIN_PASSENGER: TRAIN_METHODS.HOME_GETTRAINPASSENGER,
  SCHEDULE: TRAIN_METHODS.HOME_SCHEDULE,
  INIT: BOOK_METHODS.TRAIN_INITIALIZE,
  BOOK: BOOK_METHODS.TRAIN_BOOK,
  EXCHANGE_BOOK: BOOK_METHODS.TRAIN_EXCHANGEBOOK,
} as const;

export const TOURIST_TRAIN_FLOW_METHODS = {
  RESOURCE_STATION: TMC_METHODS.RESOURCE_TRAINSTATION,
  HOME_SEARCH: TRAIN_METHODS.HOME_SEARCH_10,
  SCHEDULE: TRAIN_METHODS.HOME_SCHEDULE_9,
  GET_EXCHANGE_INFO: TRAIN_METHODS.HOME_GETEXCHANGEINFO_5,
  GET_TRAIN_PASSENGER: TRAIN_METHODS.HOME_GETTRAINPASSENGER_6,
  REFUND: TRAIN_METHODS.HOME_REFUND,
  INIT: BOOK_METHODS.TRAIN_INITIALIZE_47,
  BOOK: BOOK_METHODS.TRAIN_BOOK_41,
  EXCHANGE_INIT: BOOK_METHODS.TRAIN_EXCHANGEINITIALIZE,
  EXCHANGE_BOOK: BOOK_METHODS.TRAIN_EXCHANGEBOOK_43,
  BIND: BOOK_METHODS.TRAIN_BIND_40,
  UNBIND: BOOK_METHODS.TRAIN_UNBIND_48,
  ACCOUNT_VALIDATE: BOOK_METHODS.TRAIN_ACCOUNTVALIDATE_39,
  CODE_VALIDATE: BOOK_METHODS.TRAIN_CODEVALIDATE_42,
  GET_CONTACTS: BOOK_METHODS.TRAIN_GETCONTACTS_46,
  GET_BIND_ACCOUNT_NUMBER: BOOK_METHODS.TRAIN_GETBINDACCOUNTNUMBER_45,
} as const;

export const TOURIST_TRAIN_BOOK_METHODS = {
  INIT: BOOK_METHODS.TRAIN_INITIALIZE_47,
  BOOK: BOOK_METHODS.TRAIN_BOOK_41,
  EXCHANGE_INIT: BOOK_METHODS.TRAIN_EXCHANGEINITIALIZE,
  EXCHANGE_BOOK: BOOK_METHODS.TRAIN_EXCHANGEBOOK_43,
} as const;

export type TrainFlowMethod =
  (typeof TRAIN_FLOW_METHODS)[keyof typeof TRAIN_FLOW_METHODS];

export type TouristTrainFlowMethod =
  (typeof TOURIST_TRAIN_FLOW_METHODS)[keyof typeof TOURIST_TRAIN_FLOW_METHODS];

export type TouristTrainBookMethod =
  (typeof TOURIST_TRAIN_BOOK_METHODS)[keyof typeof TOURIST_TRAIN_BOOK_METHODS];
