// Auto-generated by extract-methods.mjs — do not edit manually
export const TRAVEL_METHODS = {
  JYX_GETSCANINFO: "FeatureRonglvUrl-jyx-GetScanInfo",
  JYX_GETTRAVELFORMS: "FeatureRonglvUrl-jyx-GetTravelForms",
  JYX_LOGINBYTMC: "FeatureRonglvUrl-Jyx-LoginByTmc",
  JYX_REGISTERBYTMC: "FeatureRonglvUrl-Jyx-RegisterByTmc",
  JYX_SAVETRAVELFORMS: "FeatureRonglvUrl-jyx-SaveTravelForms",
  AUTHORIZE_LOAD: "HrApiUrl-Authorize-Load",
  AUTHORIZE_SUBSYSTEMS: "HrApiUrl-Authorize-SubSystems",
  INVITATION_ADD: "HrApiUrl-Invitation-Add",
  INVITATION_COSTCENTER: "HrApiUrl-Invitation-CostCenter",
  INVITATION_GETROLES: "HrApiUrl-Invitation-GetRoles",
  INVITATION_HANDLE: "HrApiUrl-Invitation-Handle",
  INVITATION_LIST: "HrApiUrl-Invitation-List",
  INVITATION_ORGANIZATION: "HrApiUrl-Invitation-Organization",
  INVITATION_POLICY: "HrApiUrl-Invitation-Policy",
  STAFF_COMFIRMINFO: "HrApiUrl-Staff-ComfirmInfo",
  STAFF_GET: "HrApiUrl-Staff-Get",
  WORKBENCH_CHANGEHR: "HrApiUrl-Workbench-ChangeHr",
  WORKBENCH_GETDATA: "HrApiUrl-Workbench-GetData",
  WORKBENCH_HRS: "HrApiUrl-Workbench-Hrs",
  WORKBENCH_LOAD: "HrApiUrl-Workbench-Load",
} as const

export type TravelMethod =
  (typeof TRAVEL_METHODS)[keyof typeof TRAVEL_METHODS];
